import type { AppId, Lesson } from './types';

export const appNames: Record<AppId, string> = {
  facetime: 'FaceTime',
  safari: 'Safari',
  finder: 'Finder',
};

export const lessons: Lesson[] = [
  {
    id: 'facetime-mic',
    app: 'facetime',
    title: 'Mute and unmute',
    description: 'Mute your microphone, then turn it back on.',
    duration: '2 steps',
    outcome: 'You practiced choosing when others can hear you.',
    prerequisite: 'For a live guide, you need a FaceTime call already in progress.',
    steps: [
      {
        id: 'mic-off',
        title: 'Mute your microphone',
        instruction: 'Click Mute.',
        why: 'Muting stops the other person from hearing you.',
        target: 'microphone',
        targetAliases: ['Mute', 'Mute Audio', 'Mute microphone', '음소거', '오디오 음소거', '마이크 끄기'],
        action: 'mic-off',
      },
      {
        id: 'mic-on',
        title: 'Unmute your microphone',
        instruction: 'Click Unmute.',
        why: 'Unmuting lets the other person hear you again.',
        target: 'microphone',
        targetAliases: ['Unmute', 'Unmute Audio', 'Unmute microphone', '음소거 해제', '오디오 음소거 해제', '마이크 켜기'],
        action: 'mic-on',
      },
    ],
  },
  {
    id: 'facetime-camera',
    app: 'facetime',
    title: 'Turn your camera off and on',
    description: 'Turn your camera off, then back on.',
    duration: '2 steps',
    outcome: 'You practiced choosing when others can see you.',
    prerequisite: 'For a live guide, you need a FaceTime call already in progress.',
    steps: [
      {
        id: 'camera-off',
        title: 'Turn your camera off',
        instruction: 'Click Turn Camera Off.',
        why: 'This hides your video. Your microphone setting stays the same.',
        target: 'camera',
        targetAliases: ['Turn Camera Off', 'Turn camera off', 'Camera Off', 'Stop Video', '카메라 끄기', '비디오 끄기', '비디오 중단'],
        action: 'camera-off',
      },
      {
        id: 'camera-on',
        title: 'Turn your camera on',
        instruction: 'Click Turn Camera On.',
        why: 'The other person can see you again.',
        target: 'camera',
        targetAliases: ['Turn Camera On', 'Turn camera on', 'Camera On', 'Start Video', '카메라 켜기', '비디오 켜기', '비디오 시작'],
        action: 'camera-on',
      },
    ],
  },
  {
    id: 'facetime-end',
    app: 'facetime',
    title: 'End a call',
    description: 'Find the button that ends your current call.',
    duration: '1 step',
    outcome: 'You practiced ending a call with the phone button.',
    prerequisite: 'For a live guide, use a FaceTime call you are ready to end.',
    steps: [
      {
        id: 'end-call',
        title: 'End the call',
        instruction: 'Click End Call.',
        why: 'This ends the current FaceTime call.',
        target: 'end-call',
        targetAliases: ['End', 'End Call', 'End call', 'Hang Up', '종료', '통화 종료', '통화 끝내기'],
        action: 'end-call',
      },
    ],
  },
  {
    id: 'safari-zoom',
    app: 'safari',
    title: 'Make text larger',
    description: 'Enlarge the text and pictures on a Safari page.',
    duration: '2 steps',
    outcome: 'You practiced making a page larger with View → Zoom In.',
    prerequisite: 'For a live guide, open a webpage in Safari.',
    requiresAccessibility: true,
    confirmation: { title: 'Text larger?', label: 'Yes, it is larger' },
    steps: [
      {
        id: 'open-view-menu',
        title: 'Open the View menu',
        instruction: 'Click View.',
        why: 'This menu has the option to enlarge the page.',
        target: 'view-menu',
        targetAliases: ['View', '보기'],
        action: 'open-view-menu',
      },
      {
        id: 'zoom-in',
        title: 'Enlarge the page',
        instruction: 'Click Zoom In.',
        why: 'This makes the page’s text and pictures larger.',
        target: 'zoom-in',
        targetAliases: ['Zoom In', '확대', '확대하기'],
        action: 'zoom-in',
        keyboardShortcuts: [
          { label: 'Zoom in', keys: ['Command', '+'] },
          { label: 'Zoom out', keys: ['Command', '−'] },
        ],
      },
    ],
  },
  {
    id: 'safari-reader',
    app: 'safari',
    title: 'Read without distractions',
    description: 'Focus on an article with Safari Reader.',
    duration: '2 steps',
    outcome: 'You practiced opening a simpler reading view.',
    prerequisite: 'Open an article that supports Reader. Some webpages do not support it.',
    requiresAccessibility: true,
    confirmation: { title: 'Reader open?', label: 'Yes, Reader is open' },
    steps: [
      { id: 'open-view-menu', title: 'Open View', instruction: 'Click View.', why: 'Reader is in the View menu.', target: 'view-menu', targetAliases: ['View', '보기'], action: 'open-view-menu' },
      { id: 'show-reader', title: 'Show Reader', instruction: 'Click Show Reader.', why: 'Reader hides extra page content so you can focus on the article.', target: 'show-reader', targetAliases: ['Show Reader', 'Show Reader View', '읽기 도구 보기', '리더 보기'], action: 'show-reader', keyboardShortcuts: [{ label: 'Show Reader', keys: ['Shift', 'Command', 'R'] }] },
    ],
  },
  {
    id: 'safari-bookmark',
    app: 'safari',
    title: 'Save this page',
    description: 'Add a bookmark so you can find the page again.',
    duration: '3 steps',
    outcome: 'You practiced saving a page as a bookmark.',
    prerequisite: 'Open a webpage you want to save in Safari. Keep the suggested name and folder.',
    requiresAccessibility: true,
    confirmation: { title: 'Page saved?', label: 'Yes, it is saved' },
    steps: [
      { id: 'open-bookmarks-menu', title: 'Open Bookmarks', instruction: 'Click Bookmarks.', why: 'This menu helps you save and return to pages.', target: 'bookmarks-menu', targetAliases: ['Bookmarks', '책갈피'], action: 'open-bookmarks-menu' },
      { id: 'add-bookmark', title: 'Add a bookmark', instruction: 'Click Add Bookmark.', why: 'Safari will suggest a name and folder.', target: 'add-bookmark', targetAliases: ['Add Bookmark', '책갈피 추가'], action: 'add-bookmark', keyboardShortcuts: [{ label: 'Add a bookmark', keys: ['Command', 'D'] }] },
      { id: 'save-bookmark', title: 'Click Add', instruction: 'Click Add.', why: 'This saves the bookmark with the suggested name and folder.', target: 'save-bookmark', targetAliases: ['Add', '추가'], action: 'save-bookmark' },
    ],
  },
  {
    id: 'safari-reopen-tab',
    app: 'safari',
    title: 'Bring back a closed tab',
    description: 'Recover the last tab you closed by mistake.',
    duration: '2 steps',
    outcome: 'You practiced bringing back a recently closed tab.',
    prerequisite: 'Use this guide after closing a Safari tab you want to bring back.',
    requiresAccessibility: true,
    confirmation: { title: 'Tab back?', label: 'Yes, it is back' },
    steps: [
      { id: 'open-history-menu', title: 'Open History', instruction: 'Click History.', why: 'History includes recently closed tabs.', target: 'history-menu', targetAliases: ['History', '방문 기록'], action: 'open-history-menu' },
      { id: 'reopen-closed-tab', title: 'Reopen the tab', instruction: 'Click Reopen Last Closed Tab.', why: 'This brings back the most recent tab you closed.', target: 'reopen-closed-tab', targetAliases: ['Reopen Last Closed Tab', '마지막으로 닫은 탭 다시 열기'], action: 'reopen-closed-tab', keyboardShortcuts: [{ label: 'Reopen the tab', keys: ['Shift', 'Command', 'T'] }] },
    ],
  },
  {
    id: 'finder-downloads',
    app: 'finder',
    title: 'Find Downloads',
    description: 'Find the folder where downloads usually go.',
    duration: '1 step',
    outcome: 'You practiced finding Downloads in Finder.',
    prerequisite: 'For a live guide, open Finder with its left sidebar visible.',
    steps: [
      {
        id: 'open-downloads',
        title: 'Open Downloads',
        instruction: 'Click Downloads.',
        why: 'With the default settings, downloads are usually saved here.',
        target: 'downloads',
        targetAliases: ['Downloads', '다운로드'],
        action: 'open-downloads',
        keyboardShortcuts: [{ label: 'Open Downloads', keys: ['Option', 'Command', 'L'] }],
      },
    ],
  },
];
