export const copy = {
  brand: {
    name: 'HelpOS',
    subtitle: 'Learn your Mac by doing',
  },
  home: {
    eyebrow: 'One step at a time',
    title: 'What would you like to learn?',
    description: 'See where to click, then try it yourself.',
    help: 'Help',
    settings: 'Settings',
    chooseMode: 'Where would you like to learn?',
    chooseLesson: 'Choose a skill to practice.',
    facetimePrerequisite: 'Live guidance needs a FaceTime call already in progress.',
    localLessons: 'These guides work without AI setup.',
  },
  modes: {
    practice: {
      label: 'Practice',
      description: 'Try the controls inside HelpOS.',
      badge: 'Practice · Your actual apps are not affected',
    },
    live: {
      label: 'On my Mac',
      description: 'See where to click in your actual apps.',
      badge: 'On my Mac · Live guide',
    },
  },
  lesson: {
    startPractice: 'Start practice',
    startLive: 'Start live guide',
    back: 'All guides',
    prerequisite: 'Before you begin',
    step: 'Step',
    why: 'What this does',
    change: 'Choose another skill',
  },
  guide: {
    targetLabel: 'Click here',
    stop: 'End guide',
    stopDescription: 'End guide only closes this guide.',
    stopFacetimeDescription: 'End guide closes this guide. It does not end your FaceTime call.',
    pause: 'Pause guide',
    paused: 'Guide paused',
    resume: 'Resume guide',
    repeat: 'Read the instruction again',
    recheck: 'Check the screen again',
    differentScreen: 'My screen looks different',
    checking: 'Looking for the button on your screen.',
    waitingForAction: 'Click the highlighted control yourself.',
    changedScreen: 'The screen changed. Checking the button location again.',
    move: 'Move guide',
    confirmTitle: 'Please check your screen.',
    confirmDescription: 'HelpOS cannot confirm this change automatically. Check the result, then confirm below.',
    confirmZoom: 'I can see the text is larger',
    confirmCallEnded: 'I can see the call has ended',
    confirmObserved: 'I checked the result',
    zoomComfort: 'Is this size comfortable to read?',
    zoomAgain: 'Show me how to enlarge it again',
    zoomFinish: 'Keep this size',
    restartDescription: 'This restarts the guide. It does not reset your actual app.',
    escapeHint: 'Press Esc to end the guide',
  },
  practice: {
    label: 'Practice',
    description: 'Only this practice screen changes. Your actual apps are not affected.',
    restart: 'Restart practice',
    wrongControl: 'Try the highlighted button for this step.',
    facetime: {
      title: 'FaceTime practice',
      participant: 'Practice partner',
      disconnected: 'Practice only · No real call',
      micOn: 'Microphone on',
      micOff: 'Microphone off',
      mute: 'Mute',
      unmute: 'Unmute',
      cameraOn: 'Camera on',
      cameraOff: 'Camera off',
      turnCameraOff: 'Turn Camera Off',
      turnCameraOn: 'Turn Camera On',
      end: 'End Call',
      ended: 'You practiced ending a call.',
      endedDescription: 'In FaceTime, this button ends the current call.',
    },
    safari: {
      title: 'Safari practice',
      view: 'View',
      zoomIn: 'Zoom In',
      pageLabel: 'Text size practice page',
      pageTitle: 'Community center guide',
      pageBody: 'Check the date and location in your program guide. If the text looks small, you can make the page larger.',
      zoomLabel: 'Page size',
    },
    finder: {
      title: 'Finder practice',
      sidebar: 'Locations',
      recent: 'Recents',
      desktop: 'Desktop',
      documents: 'Documents',
      downloads: 'Downloads',
      sampleName: 'Practice guide.pdf',
      sampleDescription: 'An example file for this practice screen.',
      folderOpened: 'You opened the Downloads folder.',
    },
  },
  result: {
    title: 'Guide complete',
    practiceVerified: 'You clicked the controls in practice.',
    observed: 'HelpOS confirmed the result in your actual app.',
    selfConfirmed: 'You confirmed the result on your screen.',
    repeat: 'Practice again',
    repeatPracticeFromLive: 'Try again in Practice',
    independent: 'Try without hints',
    showHint: 'Show me where to click',
    chooseAnother: 'Choose another guide',
    recall: 'Look for the same control next time you need it.',
  },
  confidence: {
    title: 'Learn at your own pace.',
    description: 'You can read the instructions again anytime.',
    noRush: 'There is no time limit.',
    recover: 'Check the guidance for your current screen.',
  },
  permissions: {
    title: 'HelpOS needs access to find controls',
    accessibilityTitle: 'Accessibility access',
    accessibilityDescription: 'HelpOS reads button names and locations in the open app. You do the clicking.',
    screenTitle: 'Screen Recording access',
    screenDescription: 'HelpOS can find controls by reading text on your screen. Images stay on this Mac and are not saved.',
    openSettings: 'Open Mac settings',
    setupAccessibility: 'Set up Accessibility access',
    setupScreen: 'Set up Screen Recording access',
    requesting: 'Requesting access…',
    pending: 'If macOS asks, choose whether to allow access.',
    available: 'Access is available. You can return to your guide.',
    settingsOpened: 'Mac settings opened. Access is not enabled yet.',
    enableApp: 'Turn on HelpOS. If it is missing, click + and choose HelpOS.app.',
    reopen: 'After enabling access, quit HelpOS with Command+Q and reopen it.',
    notGranted: 'Access is not enabled yet. Try setup again, then check Mac settings.',
    setupError: 'HelpOS could not finish access setup. Try again or open System Settings to check access.',
    showApp: 'Show HelpOS in Finder',
    showAppError: 'HelpOS could not show the app in Finder. Locate HelpOS.app where you installed it.',
    accessibilityIntro: 'Accessibility access lets HelpOS locate buttons. FaceTime and Safari require this permission.',
    screenAlternative: 'An alternative for finding Downloads in Finder.',
    checkAgain: 'Check access again',
    choosePractice: 'Start in Practice',
    enabled: 'Allowed',
    notEnabled: 'Setup needed',
  },
  error: {
    desktopOnlyTitle: 'Live guidance is available in the Mac app.',
    desktopOnlyDescription: 'Open the installed Mac app to follow guidance in your apps.',
    targetMissingTitle: 'HelpOS could not find the button on this screen.',
    targetMissingDescription: 'Open the app and the screen you need, then check again.',
    callRequiredTitle: 'A FaceTime call needs to be in progress.',
    callRequiredDescription: 'Bring your current FaceTime call into view.',
    differentAppTitle: 'Bring the app you are learning to the front.',
    differentAppDescription: 'HelpOS will check the screen when you return to that app.',
    permissionTitle: 'Allow access so HelpOS can find the controls.',
    observationTitle: 'HelpOS could not check the current screen.',
    observationDescription: 'Check that the app window is visible, then try again.',
    unexpectedTitle: 'The guide could not be loaded.',
    unexpectedDescription: 'Try again or close help.',
    retry: 'Try again',
    practice: 'Switch to Practice',
  },
  ai: {
    title: 'Ask AI which guide to use',
    description: 'Describe what you want to learn. AI can suggest one of the available guides.',
    placeholder: 'For example: I want to mute myself during a call.',
    ask: 'Suggest a guide',
    thinking: 'Finding a guide for you…',
    notConfigured: 'Connect AI in Settings to use this option.',
    optional: 'The guides also work without AI.',
    privacy: 'Your typed question is sent to the AI service. Screen images are not sent.',
    unsupported: 'That skill is not available yet. Choose another guide from the list.',
    error: 'AI is unavailable right now. You can still use the prepared guides.',
  },
  settings: {
    title: 'Settings',
    close: 'Close settings',
    textSize: 'Guide text size',
    standardText: 'Standard',
    largeText: 'Large',
    aiTitle: 'AI connection · Optional',
    apiKey: 'API key',
    model: 'Model',
    save: 'Apply connection',
    saved: 'AI settings applied for this session.',
    sessionOnly: 'The API key is used only while HelpOS is running. Fully quitting the app clears the connection.',
    remove: 'Disconnect AI',
    permissions: 'Mac access settings',
  },
} as const;
