import {_electron as electron} from 'playwright';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,writeFile,mkdir} from 'node:fs/promises';
const profile=await mkdtemp('/private/tmp/helpos-app-help-');
await writeFile(profile+'/call-help.json',JSON.stringify({enabled:true}));
await mkdir('test-results',{recursive:true});
const executablePath=process.argv[2];
const application=await electron.launch({...(executablePath?{executablePath,args:['--background','--user-data-dir='+profile]}:{args:['.','--background','--user-data-dir='+profile]}),cwd:process.cwd(),timeout:30000});
const results=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const until=async check=>{const end=Date.now()+20000;while(Date.now()<end){if(await check())return;await sleep(100);}throw Error('Timed out waiting for app help');};
const windows=()=>application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().map(w=>({url:w.webContents.getURL(),visible:w.isVisible(),focused:w.isFocused()})));
// A native BrowserWindow can be visible before Playwright attaches its Page.
// Wait for the owned loaded route as well; about:blank is never a home page.
const pageForRoute=async hash=>{
 let page;
 await until(()=>{page=application.windows().find(p=>!p.isClosed()&&p.url().endsWith('/index.html'+hash));return !!page;});
 await page.waitForLoadState('domcontentloaded',{timeout:20000});
 return page;
};
const wake=async(bundle='com.apple.FaceTime',id=randomUUID(),at=Date.now())=>{await application.evaluate(({app},v)=>{globalThis.__appHelpTest.bundle=v.bundle;app.emit('second-instance',{},['HelpOS','--background','--app-help',v.bundle,'--activation-id',v.id,'--activation-at',String(v.at)]);},{bundle,id,at});return{id,at};};
try {
 await sleep(400);assert.deepEqual(await windows(),[]);
 await application.evaluate(({app,BrowserWindow,globalShortcut})=>{
  Object.defineProperty(app,'isPackaged',{configurable:true,get:()=>true});
  globalThis.__appHelpTest={writes:[],osStatus:'not-registered',enabled:false,bundle:'com.apple.FaceTime',window:{x:100,y:100,width:800,height:600},reads:0,callDecodes:0,liveDecodes:0,delay:true};
  const shortcuts=new Set();globalShortcut.register=k=>{shortcuts.add(k);return true;};globalShortcut.unregister=k=>shortcuts.delete(k);globalShortcut.unregisterAll=()=>shortcuts.clear();globalShortcut.isRegistered=k=>shortcuts.has(k);
  app.getLoginItemSettings=options=>{const t=globalThis.__appHelpTest;if(options?.type!=='agentService'||options?.serviceName!=='app.helpos.app-watcher.plist')throw Error('Unexpected main login access');return{openAtLogin:t.enabled,status:t.osStatus,wasOpenedAtLogin:false};};
  app.setLoginItemSettings=options=>{const t=globalThis.__appHelpTest;t.writes.push(options);if(!t.refuse){t.enabled=options.openAtLogin;t.osStatus=options.openAtLogin?'enabled':'not-registered';}};
  const load=BrowserWindow.prototype.loadFile;
  BrowserWindow.prototype.loadFile=async function(file,options){const t=globalThis.__appHelpTest;if(options?.hash==='call-help'&&t.delay){t.delay=false;await new Promise(r=>t.release=r);}return load.call(this,file,options);};
  const k=process.mainModule.require(app.getAppPath() + '/node_modules/koffi'),decode=k.decode;
  const loadNative=k.load;const nativePath=process.cwd()+'/native/libhelpos-observer.dylib';
  k.load=function(file,...args){return loadNative.call(k,String(file).endsWith('libhelpos-observer.dylib')?nativePath:file,...args);};
  k.decode=function(pointer,type,...args){const value=decode.call(k,pointer,type,...args);if(type!=='char'||typeof value!=='string')return value;let real;try{real=JSON.parse(value);}catch{return value;}if(!real||typeof real!=='object')return value;const t=globalThis.__appHelpTest;if(Object.hasOwn(real,'callId')&&Object.hasOwn(real,'accessibility')&&Object.hasOwn(real,'state')){t.callDecodes++;return JSON.stringify({accessibility:true,state:'inactive',callId:null,window:null,timestamp:Date.now()});}if(Object.hasOwn(real,'elements')&&Object.hasOwn(real,'source')&&Object.hasOwn(real,'frontmostBundleId')){t.liveDecodes++;return JSON.stringify({trusted:true,screenCapture:false,frontmostBundleId:'com.apple.Safari',frontmostName:'Safari',source:'accessibility',timestamp:Date.now(),window:t.window,windowId:'fixture-safari',elements:[{id:'view',label:'View',role:'AXMenuBarItem',enabled:true,rect:{x:200,y:0,width:50,height:24}}]});}if(!Object.hasOwn(real,'pid')||!Object.hasOwn(real,'frontmostBundleId'))return value;t.reads++;return JSON.stringify({frontmostBundleId:t.bundle,pid:123,window:t.noWindow?null:t.window,timestamp:Date.now()});};
 });
 await wake();await sleep(250);assert.deepEqual(await windows(),[]);
 assert.deepEqual(await application.evaluate(()=>globalThis.__appHelpTest.writes),[]);
 results.push('Quiet launch and legacy enabled JSON never register the watcher or open home; Off ignores app events');
 await application.evaluate(()=>{const t=globalThis.__appHelpTest;t.osStatus='enabled';t.enabled=true;});
 await wake();await until(()=>application.evaluate(()=>typeof globalThis.__appHelpTest.release==='function'));
 assert.equal(await application.evaluate(({globalShortcut})=>globalShortcut.isRegistered('Escape')),false);
 assert.equal((await windows()).some(w=>w.visible),false);
 await application.evaluate(()=>{const t=globalThis.__appHelpTest;t.enabled=false;t.osStatus='not-registered';t.release();});
 await sleep(700);assert.equal((await windows()).some(w=>w.visible),false);
 results.push('External Off while the popup is loading prevents delayed reveal and leaves Escape free');
 await application.evaluate(()=>{const t=globalThis.__appHelpTest;t.enabled=true;t.osStatus='enabled';});
 const episode=await wake('com.apple.FaceTime');
 await until(async()=> (await windows()).some(w=>w.url.endsWith('#call-help')&&w.visible));
 const offer=await pageForRoute('#call-help');
 await offer.getByRole('heading',{name:'FaceTime help'}).waitFor();
 assert.equal((await windows()).find(w=>w.url.endsWith('#call-help')).focused,false);
 assert.equal((await windows()).length,1);
 assert.equal((await offer.evaluate(()=>window.helpOS.getCallHelpState())).suggestion.source,'activation');
 await assert.rejects(offer.evaluate(()=>window.helpOS.getLiveState()));
 assert.equal((await windows()).some(w=>/#coach|#overlay/.test(w.url)),false);
 assert.equal(await offer.getByText(/call detected/i).count(),0);
 results.push('Fresh FaceTime activation opens a passive selection card without claiming a call or starting a guide');
 await offer.evaluate(()=>window.helpOS.dismissCallHelp());
 await wake('com.apple.FaceTime',episode.id,episode.at);await sleep(200);
 assert.equal((await windows()).some(w=>w.visible),false);
 results.push('Dismissed visit IDs cannot reopen an offer');
 for(const[bundle,name]of[['com.apple.Safari','Safari'],['com.apple.finder','Finder']]){await wake(bundle);await offer.getByRole('heading',{name:name+' help'}).waitFor();assert.equal((await offer.evaluate(()=>window.helpOS.getCallHelpState())).suggestion.app,name.toLowerCase());await offer.evaluate(()=>window.helpOS.dismissCallHelp());}
 results.push('Safari and Finder activation events select their own app cards');
 const safariEpisode=await wake('com.apple.Safari');
 await until(async()=> (await windows()).some(w=>w.url.endsWith('#call-help')&&w.visible));
 await offer.getByRole('heading',{name:'Safari help',exact:true}).waitFor();
 await offer.evaluate(()=>window.helpOS.dismissCallHelp());
 const beforeReopenReads=await application.evaluate(()=>globalThis.__appHelpTest.reads);
 const reopenedWindow={x:220,y:120,width:900,height:650};
 await application.evaluate((_electron,value)=>{globalThis.__appHelpTest.window=value;},reopenedWindow);
 await wake('com.apple.Safari',safariEpisode.id);await sleep(200);
 assert.equal((await windows()).some(w=>w.visible),false);
 assert.equal(await application.evaluate(()=>globalThis.__appHelpTest.reads),beforeReopenReads);
 const reopened=await wake('com.apple.Safari');
 await until(async()=> (await windows()).some(w=>w.url.endsWith('#call-help')&&w.visible));
 assert.deepEqual((await offer.evaluate(()=>window.helpOS.getCallHelpState())).suggestion,{id:reopened.id,source:'activation',app:'safari',window:reopenedWindow});
 results.push('A fresh Safari window episode reopens its dismissed card without changing foreground apps; the old UUID stays consumed');
 await offer.evaluate(()=>window.helpOS.chooseCallHelpLesson('safari-zoom'));
 const coach=await pageForRoute('#coach');
 await until(async()=> (await coach.evaluate(()=>window.helpOS.getLiveState())).status==='guiding');
 const guideSession=(await coach.evaluate(()=>window.helpOS.getLiveState())).sessionId;
 const beforeBusyReads=await application.evaluate(()=>globalThis.__appHelpTest.reads);
 const busyEpisode=await wake('com.apple.Safari');await sleep(200);
 assert.equal((await coach.evaluate(()=>window.helpOS.getLiveState())).sessionId,guideSession);
 assert.equal((await coach.evaluate(()=>window.helpOS.getLiveState())).status,'guiding');
 assert.equal((await windows()).some(w=>w.url.endsWith('#call-help')&&w.visible),false);
 await coach.evaluate(()=>window.helpOS.pauseLive());
 const pausedEpisode=await wake('com.apple.Safari');await sleep(200);
 const pausedState=await coach.evaluate(()=>window.helpOS.getLiveState());
 assert.equal(pausedState.sessionId,guideSession);assert.equal(pausedState.status,'paused');
 assert.equal((await windows()).some(w=>w.url.endsWith('#call-help')&&w.visible),false);
 assert.equal(await application.evaluate(()=>globalThis.__appHelpTest.reads),beforeBusyReads);
 await coach.evaluate(()=>window.helpOS.stopLive());
 await until(async()=> !(await windows()).some(w=>w.visible));
 for(const consumed of[busyEpisode,pausedEpisode]){await wake('com.apple.Safari',consumed.id);await sleep(200);assert.equal((await windows()).some(w=>w.visible),false);}
 assert.equal(await application.evaluate(()=>globalThis.__appHelpTest.reads),beforeBusyReads);
 await wake('com.apple.Safari');
 await until(async()=> (await windows()).some(w=>w.url.endsWith('#call-help')&&w.visible));
 await offer.evaluate(()=>window.helpOS.dismissCallHelp());
 results.push('Active and explicitly paused Safari guides consume window episodes without replacement, automatic resume, or delayed replay after closing');
 await wake('com.apple.Terminal');await sleep(200);assert.equal((await windows()).some(w=>w.visible),false);
 await application.evaluate(()=>{globalThis.__appHelpTest.noWindow=true;});await wake('com.apple.finder');await sleep(250);assert.equal((await windows()).some(w=>w.visible),false);
 await application.evaluate(()=>{globalThis.__appHelpTest.noWindow=false;});
 results.push('Unsupported apps and Finder without a normal visible window cannot show help');
 await application.evaluate(({app})=>app.emit('activate'));
 await until(async()=> (await windows()).some(w=>w.url.endsWith('/index.html')&&w.visible));
 const home=await pageForRoute('');await home.getByRole('heading',{name:'What would you like to do?'}).waitFor();
 await assert.rejects(home.evaluate(()=>window.helpOS.setCallHelpEnabled('true')));
 const automatic=home.getByRole('switch',{name:'Show help when I open supported apps',exact:true});
 await automatic.waitFor();await until(()=>automatic.isEnabled());assert.equal(await automatic.isChecked(),true);
 assert.deepEqual(await application.evaluate(()=>globalThis.__appHelpTest.writes),[]);
 await automatic.click();await until(async()=>!(await automatic.isChecked()));
 await home.getByRole('button',{name:'Settings',exact:true}).click();assert.equal(await automatic.isChecked(),false);
 await automatic.click();await until(()=>automatic.isChecked());
 await home.keyboard.press('Escape');assert.equal(await automatic.isChecked(),true);
 assert.deepEqual(await application.evaluate(()=>globalThis.__appHelpTest.writes),[false,true].map(openAtLogin=>({type:'agentService',serviceName:'app.helpos.app-watcher.plist',openAtLogin})));
 await application.evaluate(()=>{globalThis.__appHelpTest.refuse=true;});await assert.rejects(home.evaluate(()=>window.helpOS.setCallHelpEnabled(false)));assert.equal((await home.evaluate(()=>window.helpOS.getCallHelpState())).enabled,true);
 await application.evaluate(()=>{globalThis.__appHelpTest.refuse=false;});await home.evaluate(()=>window.helpOS.setCallHelpEnabled(false));
 results.push('Home and Settings share the confirmed switch; explicit clicks write only the named watcher service and require OS readback');
 await home.evaluate(()=>window.helpOS.previewCallHelp('safari'));await offer.getByText('Demo preview',{exact:true}).waitFor();
 await wake('com.apple.FaceTime');assert.equal((await home.evaluate(()=>window.helpOS.getCallHelpState())).suggestion.app,'safari');
 await offer.evaluate(()=>window.helpOS.chooseCallHelpLesson('safari-zoom'));await until(async()=> (await windows()).some(w=>w.url.endsWith('/index.html')&&w.visible));
 await home.getByRole('heading',{name:'What would you like to do?',exact:true}).waitFor();
 assert.equal(await home.locator('.practice-page, .tutorial-scrim').count(),0);
 assert.equal(await home.getByRole('button',{name:'Open voice guide',exact:true}).isVisible(),true);
 assert.equal((await home.evaluate(()=>window.helpOS.getLiveState())).status,'idle');
 results.push('Internal preview while Off returns to live-only Home without starting a lesson; activation does not replace the offer');
 await writeFile('test-results/app-help-desktop-results.json',JSON.stringify({packaged:!!executablePath,results,nativeDecodes:await application.evaluate(()=>({context:globalThis.__appHelpTest.reads,call:globalThis.__appHelpTest.callDecodes,live:globalThis.__appHelpTest.liveDecodes})),note:'Real Electron windows, preload and native decode; app-context observations, live Safari targets, and OS agent registration are injected fixtures. All recognized call-state results are replaced with inactive fixtures after real pointer decoding, so a real user call cannot trigger help in this suite. No real watcher registration, application activation, or call action occurs in this suite.'},null,2));
 console.log('PASS',results.length,'app-trigger desktop checks');
}catch(error){await writeFile('test-results/app-help-desktop-results.json',JSON.stringify({results,failure:String(error),windows:await windows()},null,2));console.error(error);process.exitCode=1;}finally{await application.close();}
