import { _electron as electron } from 'playwright';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';

const run=promisify(execFile);
await mkdir('test-results',{recursive:true});
const application=await electron.launch({args:['.'],cwd:process.cwd(),timeout:30000});
const results=[];
try {
  const page=await application.firstWindow();
  await page.getByRole('heading',{name:'What would you like to do?'}).waitFor();
  await page.evaluate(()=>window.helpOS.startLive('safari-zoom'));
  await run('/usr/bin/open',['-a','Safari',path.resolve('public/reading-practice.html')]);
  let state;
  const deadline=Date.now()+25000;
  do {
    state=await page.evaluate(()=>window.helpOS.getLiveState());
    if(state.status==='guiding'&&state.target&&state.observationSource!=='none')break;
    await new Promise(resolve=>setTimeout(resolve,200));
  }while(Date.now()<deadline);
  assert.equal(state.stepIndex,0);assert.equal(state.verification,null);assert.ok(state.target);
  results.push({name:'Actual Safari menu position observed',passed:true,state});
  console.log('REAL SAFARI TARGET',JSON.stringify(state));
  const windows=await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().map(window=>({url:window.webContents.getURL(),visible:window.isVisible(),focusable:window.isFocusable(),bounds:window.getBounds()})));
  const overlayInfo=windows.find(window=>window.url.endsWith('#overlay'));
  const coachInfo=windows.find(window=>window.url.endsWith('#coach'));
  assert.ok(overlayInfo?.visible);assert.equal(overlayInfo.focusable,false);assert.ok(coachInfo?.visible);
  const overlap=(a,b)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
  assert.equal(overlap(state.target,coachInfo.bounds),false);
  const overlay=application.windows().find(window=>window.url().endsWith('#overlay'));
  const highlighted=await overlay.locator('.native-target').boundingBox();
  console.log('OVERLAY GEOMETRY',JSON.stringify({highlighted,overlayInfo,window:await overlay.evaluate(()=>({x:screenX,y:screenY,width:innerWidth,height:innerHeight,style:document.querySelector('.native-target')?.getAttribute('style')}))}));
  assert.ok(highlighted);assert.ok(Math.abs(highlighted.x+overlayInfo.bounds.x-(state.target.x-6))<2);
  assert.ok(Math.abs(highlighted.y+overlayInfo.bounds.y-(state.target.y-6))<2);
  assert.equal(await overlay.locator('.tutorial-scrim').count(),1);
  const png=await overlay.screenshot({omitBackground:true});
  const pixels=await overlay.evaluate(async({data,x,y})=>{
    const image=new Image();image.src=`data:image/png;base64,${data}`;await image.decode();
    const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;
    const context=canvas.getContext('2d');context.drawImage(image,0,0);
    const scale=image.naturalWidth/innerWidth;
    return {hole:context.getImageData(Math.round(x*scale),Math.round(y*scale),1,1).data[3],background:context.getImageData(Math.round(1000*scale),Math.round(700*scale),1,1).data[3]};
  },{data:png.toString('base64'),x:state.target.x-overlayInfo.bounds.x+state.target.width/2,y:state.target.y-overlayInfo.bounds.y+state.target.height/2});
  assert.ok(pixels.hole<10,`The target hole should remain transparent: ${JSON.stringify(pixels)}`);
  assert.ok(pixels.background>=140&&pixels.background<=155,`The surrounding screen should be dimmed: ${JSON.stringify(pixels)}`);
  results.push({name:'Actual native mask keeps target transparent and dims surroundings at58%',passed:true,pixels});
  const observed=JSON.parse((await run(path.resolve('native/helpos-observer'),['--probe'])).stdout);
  assert.equal(observed.frontmostBundleId,'com.apple.Safari');
  results.push({name:'Real overlay positioned correctly, coach clear of target, Safari retains foreground',passed:true,windows});
  const crop=[Math.floor(state.target.x-12),Math.max(0,Math.floor(state.target.y-10)),Math.ceil(state.target.width+24),Math.ceil(state.target.height+24)];
  await run('/usr/sbin/screencapture',['-x',`-R${crop.join(',')}`,path.resolve('test-results/native-safari-view-highlight.png')]);
  const coach=application.windows().find(window=>window.url().endsWith('#coach'));
  const whitePoint=[coachInfo.bounds.x+coachInfo.bounds.width-30,coachInfo.bounds.y+22,4,4];
  const pointPath=path.resolve('test-results/native-coach-layer-pixel.png');
  await run('/usr/sbin/screencapture',['-x',`-R${whitePoint.join(',')}`,pointPath]);
  const coachPixel=await coach.evaluate(async data=>{
    const image=new Image();image.src=`data:image/png;base64,${data}`;await image.decode();
    const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;
    const context=canvas.getContext('2d');context.drawImage(image,0,0);
    return [...context.getImageData(1,1,1,1).data];
  },(await readFile(pointPath)).toString('base64'));
  assert.ok(coachPixel.slice(0,3).every(value=>value>220),`Actual coach should stay bright above dim layer: ${JSON.stringify(coachPixel)}`);
  results.push({name:'Screen pixel confirms native coach remains bright above dim layer',passed:true,pixel:coachPixel});
  const defaultReading=await coach.locator('.native-coach-body').evaluate(element=>({height:element.clientHeight,scrollHeight:element.scrollHeight}));
  assert.ok(defaultReading.scrollHeight<=defaultReading.height+1,`Default native instruction and purpose should fit without scrolling: ${JSON.stringify(defaultReading)}`);
  results.push({name:'Default English native instruction and purpose fit without scrolling',passed:true,reading:defaultReading});
  await coach.screenshot({path:'test-results/native-spotlight-coach.png',omitBackground:true});
  await page.evaluate(()=>localStorage.setItem('helpos:text-scale','2'));
  const scaledDeadline=Date.now()+10000;
  let scaled;
  do {
    scaled=await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.webContents.getURL().endsWith('#coach')).getBounds());
    if(scaled.width>=700)break;
    await new Promise(resolve=>setTimeout(resolve,100));
  }while(Date.now()<scaledDeadline);
  assert.ok(scaled.width>=700,`Coach should grow for200% text: ${JSON.stringify(scaled)}`);
  const reading=await coach.locator('.native-coach-body').evaluate(element=>({height:element.clientHeight,lineHeight:parseFloat(getComputedStyle(element.querySelector('h2')).lineHeight)}));
  assert.ok(reading.height>=reading.lineHeight*2,`200% instruction remains readable: ${JSON.stringify(reading)}`);
  const stop=await coach.getByRole('button',{name:'End guide',exact:true}).boundingBox();
  assert.ok(stop&&stop.y+stop.height<=scaled.height,'Native stop is visible at200%');
  assert.equal(overlap(state.target,scaled),false);
  await coach.screenshot({path:'test-results/native-spotlight-coach-200.png',omitBackground:true});
  results.push({name:'Real native coach scales with200% preference, remains readable and avoids target',passed:true,bounds:scaled,reading});
  await page.evaluate(()=>localStorage.setItem('helpos:text-scale','1'));
  await page.evaluate(()=>window.helpOS.pauseLive());
  assert.equal((await page.evaluate(()=>window.helpOS.getLiveState())).status,'paused');
  assert.equal(await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.webContents.getURL().endsWith('#overlay')).isVisible()),false);
  await page.evaluate(()=>window.helpOS.stopLive());
  assert.equal((await page.evaluate(()=>window.helpOS.getLiveState())).status,'idle');
  results.push({name:'Pause and stop remove actual overlay',passed:true});
  await writeFile('test-results/native-safari-results.json',JSON.stringify({results,note:'Observed real Safari and native overlay. No synthetic OS click was sent; native menu selection and zoom completion were not exercised here.'},null,2));
  console.log('PASS actual Safari observation, overlay alignment, focus retention, pause/stop');
} catch(error) {
  const page=application.windows().find(window=>!/#(coach|overlay)$/.test(window.url()));
  const state=page?await page.evaluate(()=>window.helpOS?.getLiveState()).catch(()=>null):null;
  await writeFile('test-results/native-safari-results.json',JSON.stringify({results,state,failure:String(error)},null,2));
  console.error(error);console.log('LAST STATE',JSON.stringify(state));process.exitCode=1;
} finally {await application.close();}
